In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
with open('/content/drive/MyDrive/Clark_et_al_2022_PNAS_SM/foodDB_dat/products anonymised.csv', 'rb') as f:
    product_data = pd.read_csv(f,encoding="ISO-8859-1")
with open('/content/drive/MyDrive/Clark_et_al_2022_PNAS_SM/foodDB_dat/categories anonymised.csv', 'rb') as f:
    cat_data = pd.read_csv(f,encoding="ISO-8859-1")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
salt_data = product_data[['product_id','salt_per_100']]

In [5]:
salt_data['salt_per_100']= salt_data['salt_per_100'].map(lambda x: str(x)[:-1])
for i in range(len(salt_data)):
  if salt_data['salt_per_100'].iloc[i] == '<0.01':
      salt_data['salt_per_100'].iloc[i] = '0.01'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [4]:
cat_data

        product_id  name  main_category  department  aisle  shelf
0         11891023  2815             19          12   1715    192
1         11891023  2818             19          84     41    192
2         11891023  2819             19          84    455    192
3         11891024  2815             19          12   1715    192
4         11891024  3029             19         402    119    192
...            ...   ...            ...         ...    ...    ...
230877    11902426   605              8         492   1715    192
230878    11902427   605              8         492   1715    192
230879    11902428   605              8         492   1715    192
230880    11902429   605              8         492   1715    192
230881    11902430   605              8         492   1715    192

[230882 rows x 6 columns]

In [5]:
product_data

,product_id,snapshot_id,product_list_name,product_name,url,ingredients_text,energy_per_100,fat_per_100,saturates_per_100,salt_per_100,sugar_per_100,carbohydrate_per_100,protein_per_100,fibre_per_100,serving,serving_data,serving_value,serving_unit,Retailer
0,11891023,1075,10892,11047,81696,Cheddar,NaN,34.9g,21.7g,1.8g,0.1g,0.1g,25.4g,NaN,NaN,NaN,NaN,NaN,2918
1,11891024,1075,70699,71680,83821,"Butter (Milk), Salt (1.5%).",NaN,82.2g,52.1g,1.5g,0.6g,0.6g,0.6g,0g,10 g,NaN,10,g,2918
2,11891025,1075,70002,70928,85460,Salmon (Fish).,NaN,12.0g,1.6g,0.1g,0g,0g,25.3g,0g,94 g,NaN,94,g,2918
3,11891026,1075,31053,31483,83377,"Clementine, Mandarin",NaN,0.2g,0g,<0.01g,9.6g,9.6g,0.9g,1.5g,NaN,NaN,NaN,NaN,2918
4,11891027,1075,75024,76105,77507,Avocado,NaN,19.5g,4.1g,0.1g,0.5g,1.9g,1.9g,3.4g,80 g,NaN,80,g,2918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101161,11902756,1082,23607,23958,29925,"Mascarpone cream 50% [water, mascarpone 11% (M...",973 kj,13g,9.5g),0.14g,16g),24g,4.5g,1.3g,NaN,NaN,NaN,NaN,6511
101162,11902757,1082,23595,23946,29694,"Sauce 38.7% (fishandcrustaceanstock (water,FIS...",678 kj,16g,2.1g),0.52g,1.7g),2.6g,2.1g,0.7g,NaN,NaN,NaN,NaN,6511
101163,11902758,1082,23608,23959,29699,"Pecorino bÌ©chamel sauce 32% [water, skimmedMI...",505 kj,6.0g,3.1g),0.8g,3.2g),11g,5.0g,1.4g,NaN,NaN,NaN,NaN,6511
101164,11902759,1082,23603,23954,29697,"Tomato sauce 55.6% [tomato puree, onion, water...",539 kj,6.2g,2.7g),0.6g,3.0g),4.1g,13.0g,1.3g,NaN,NaN,NaN,NaN,6511
101165,11902760,1082,23591,23942,29692,"Clam salsa 44.4% (clam stock (MOLLUSCS), olive...",814 kj,20g,2.6g),0.33g,1.2g),3.0g,1.6g,0.9g,NaN,NaN,NaN,NaN,6511

In [4]:
data = pd.merge(product_data,cat_data, how='left', on=['product_id'])

In [5]:
data['ingredients_text'].shape
data.dropna(axis=0,subset = ['ingredients_text'])

,product_id,snapshot_id,product_list_name,product_name,url,ingredients_text,energy_per_100,fat_per_100,saturates_per_100,salt_per_100,...,serving,serving_data,serving_value,serving_unit,Retailer,name,main_category,department,aisle,shelf
0,11891023,1075,10892,11047,81696,Cheddar,NaN,34.9g,21.7g,1.8g,...,NaN,NaN,NaN,NaN,2918,2815,19,12,1715,192
1,11891023,1075,10892,11047,81696,Cheddar,NaN,34.9g,21.7g,1.8g,...,NaN,NaN,NaN,NaN,2918,2818,19,84,41,192
2,11891023,1075,10892,11047,81696,Cheddar,NaN,34.9g,21.7g,1.8g,...,NaN,NaN,NaN,NaN,2918,2819,19,84,455,192
3,11891024,1075,70699,71680,83821,"Butter (Milk), Salt (1.5%).",NaN,82.2g,52.1g,1.5g,...,10 g,NaN,10,g,2918,2815,19,12,1715,192
4,11891024,1075,70699,71680,83821,"Butter (Milk), Salt (1.5%).",NaN,82.2g,52.1g,1.5g,...,10 g,NaN,10,g,2918,3029,19,402,119,192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232324,11902756,1082,23607,23958,29925,"Mascarpone cream 50% [water, mascarpone 11% (M...",973 kj,13g,9.5g),0.14g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232325,11902757,1082,23595,23946,29694,"Sauce 38.7% (fishandcrustaceanstock (water,FIS...",678 kj,16g,2.1g),0.52g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232326,11902758,1082,23608,23959,29699,"Pecorino bÌ©chamel sauce 32% [water, skimmedMI...",505 kj,6.0g,3.1g),0.8g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232327,11902759,1082,23603,23954,29697,"Tomato sauce 55.6% [tomato puree, onion, water...",539 kj,6.2g,2.7g),0.6g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232328,11902760,1082,23591,23942,29692,"Clam salsa 44.4% (clam stock (MOLLUSCS), olive...",814 kj,20g,2.6g),0.33g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192

In [6]:
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace('percent','%'))
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace(';',','))
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace('[','('))
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace(']',')'))
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace('{','('))
data.ingredients_text = data.ingredients_text.apply(lambda x: str(x).replace('}',')'))

data.ingredients_text = data.ingredients_text.apply(lambda x: str(x.lower()).replace(x[x.find('allergy advice'):],' '))

In [10]:
# dat = data.iloc[232327]

data.ingredients_text.iloc[232326]
dat = data.iloc[232326]

In [7]:
import re

In [8]:
text2 = data.ingredients_text.iloc[232327]

In [11]:
from pandas.io.formats.info import DataFrameInfo
import math
import re
dat.ingredients_text
text = dat.ingredients_text
text2

"tomato sauce 55.6% (tomato puree, onion, water, chic en stoc  (water, chic en, salt), double tomato concentrate, olive oil, garlic, salt), roast chic en breast fillet 27.8% (chic en breast, rice starch, salt, dextrose, xylose, maltodextrin), smo ed provola cheese 8.3% (mil , salt, lactic ferments, microbial rennet, natural smo e), semi-dried cherry tomatoes 5.6%, pecorino romano cheese 2.8% (sheep'smil , rennet, salt, lactic ferments).allergy advice: for allergen, see ingredients in bold. warning! although every effort has been made to remove all bones, some may remain.contains:mil "

In [30]:
search_words.iloc[3]

LCA_Category                                         Maize (Meal)
Search_Words    [\bmaize\b, \bcorn(s)?\b, \bsweetcorn\b, \bcor...
Name: 3, dtype: object

In [28]:
search_words = pd.read_csv('/content/drive/MyDrive/Clark_et_al_2022_PNAS_SM/Data Inputs/Search words 6April2020 try2.csv')
search_words.head()
search_words.Search_Words = search_words.Search_Words.apply(lambda X: re.split('\\|',X))

In [29]:
search_words.iloc[3].Search_Words

['\\bmaize\\b',
 '\\bcorn(s)?\\b',
 '\\bsweetcorn\\b',
 '\\bcornflour(s)?\\b',
 '\\bcornstarch\\b',
 '\\bmaizestarch\\b',
 'babycorn',
 'popcorn',
 'cornmeal',
 'cornflake(s)?',
 'flakesmaize',
 'cornflour']

In [61]:
print(ret)
x = data[data.Retailer==684]
dep = np.unique(list(x.department))
loops = len(dep)

x = x[x.department==dep[2]]

[ 684 2238 2918 3652 4840 5729 6511 8360]

In [88]:
# c =inside_par(10,da.iloc[0])
c

product_id                                                       11916311
snapshot_id                                                          1079
product_list_name                                                   89020
product_name                                                        90225
url                                                                 13020
ingredients_text        free rangeeggwhi e, skimmedmilk, maize s arch,...
energy_per_100                                                     1036kj
fat_per_100                                                            8g
saturates_per_100                                                    1.1g
salt_per_100                                                        0.54g
sugar_per_100                                                        0.4g
carbohydrate_per_100                                                33.9g
protein_per_100                                                      9.2g
fibre_per_100                                                        1.2g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             8360
name                                                                 3345
main_category                                                          20
department                                                            582
aisle                                                                1715
shelf                                                                 192
string0                 sunflower leci hins, mono- and di-glycerides o...
ing_string0                                                             8
string1                                                       xan han gum
ing_string1                                                             9
Name: 192256, dtype: object

In [30]:
ret = np.unique(list(da.Retailer))
ret

array([ 684, 2238, 2918, 3652, 4840, 5729, 6511, 8360])

In [12]:
da = data.copy()

In [45]:
d.iloc[10].ingredients_text

'flour,  ultana , butter,  ugar,yolk, candied citru  fruit peel (orange and citru  peel, gluco e-fructo e  yrup,  ugar), natural yea t, emul ifying agent : mono-diglyceride  of fatty acid ,  alt,  kimmedpowder, flavouring '

In [59]:
d=d.iloc[0:100]
d

,product_id,snapshot_id,product_list_name,product_name,url,ingredients_text,energy_per_100,fat_per_100,saturates_per_100,salt_per_100,...,serving,serving_data,serving_value,serving_unit,Retailer,name,main_category,department,aisle,shelf
108367,11904331,1077,23369,23718,40071,"potato starch, aize starch, water, sunflower ...",1335kj,8.4g,0.7g,1.43g,...,125 g,NaN,125,g,3652,54,3,55,1799,192
152335,11959235,1077,34817,35278,44329,a,NaN,NaN,4.6,NaN,...,NaN,NaN,NaN,NaN,3652,42,3,55,934,192
156500,11961654,1077,29293,29705,42625,"flour (with a e calcium, iron, niacin, thiam...",987kj,1.7g,0.3g,0.90g,...,40 g,NaN,40,g,3652,68,3,55,2523,192
156501,11961655,1077,29337,29748,42640,"flour (with a e calcium, iron, niacin, thiam...",987kj,1.7g,0.3g,0.90g,...,50 g,NaN,50,g,3652,68,3,55,2523,192
156502,11961656,1077,33671,34117,44072,"flour (with calcium, iron, niacin (b3 and thi...",NaN,2.0 g,0.6 g,0.95 g,...,NaN,NaN,NaN,NaN,3652,68,3,55,2523,192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156638,11961719,1077,29339,29750,42641,"wholemeal flou (), wate , yeast, ca amelised ...",934kj,1.8g,0.4g,0.90g,...,29 g,NaN,29,g,3652,70,3,55,2543,192
156639,11961719,1077,29339,29750,42641,"wholemeal flou (), wate , yeast, ca amelised ...",934kj,1.8g,0.4g,0.90g,...,29 g,NaN,29,g,3652,40,3,55,370,192
156640,11961720,1077,83520,84689,57965,"wholemealflour, wa er*, mixed seeds (20%) (mil...",NaN,9.3g,1.2g,0.80g,...,NaN,NaN,NaN,NaN,3652,70,3,55,2543,192
156641,11961720,1077,83520,84689,57965,"wholemealflour, wa er*, mixed seeds (20%) (mil...",NaN,9.3g,1.2g,0.80g,...,NaN,NaN,NaN,NaN,3652,60,3,55,2154,192
156642,11961720,1077,83520,84689,57965,"wholemealflour, wa er*, mixed seeds (20%) (mil...",NaN,9.3g,1.2g,0.80g,...,NaN,NaN,NaN,NaN,3652,40,3,55,370,192

In [61]:
d = da[da.Retailer==3652]
dep = np.unique(list(d.department))
loops = len(dep)
extract_embeding = 10
d=d[d.department==dep[6]]
d=d.iloc[0:5]
l=[]
for row in range(len(d)):
  x = inside_par(10,d.iloc[row])
  l.append(x)

KeyboardInterrupt: ignored

In [109]:
# ret = list(da.Retailer)
# ret = np.unique(ret)
ret = [684]
search_words = pd.read_csv('/content/drive/MyDrive/Clark_et_al_2022_PNAS_SM/Data Inputs/Search words 6April2020 try2.csv')
search_words.Search_Words = search_words.Search_Words.apply(lambda X: re.split('\\|',X))
for i in ret:
  d = da[da.Retailer==i]
  dep = np.unique(list(d.department))
  loops = len(dep)
  extract_embeding = 10
  for z in range(loops):
    data = d[d.department==dep[z]]
    l=[]
    # for row in range(len(d)):
    #   x = inside_par(10,d.iloc[row])
    #   l.append(x)

    # d = inside_par(extract_embeding,d)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer_missing(indexer, value)

KeyboardInterrupt: ignored

In [21]:
def find_inside(text,i):
  if text.find('(',i) is not None:
      f_open = text.find('(',i)+1
  else: f_open = 0
  if text.find(')',f_open) is not None:
     close = text.find(')',f_open)
  else: close = 0
  while text[f_open:close].count('(') != text[f_open:close].count(')'):
    close = text.find(')',close+1)
  else: f_close = close
  return f_open,f_close

In [17]:
from collections import Counter
num_embedded = 10
text = dat.ingredients_text
i = 0
count = 0
for j in range(num_embedded):
    open, close = find_inside(text,i)
    if open !=0 and close !=0:
      dat['string'+str(j)] = dat.ingredients_text[open:close]
      count += dat.ingredients_text[open:close].count(',')
      count_row = dat.ingredients_text[0:close].count(',') - count
      dat['ing_string'+str(j)] = count_row
    else: break
    i = close+1

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer_missing(indexer, value)

In [22]:
def inside_par (num_embedded,dat):
    text = dat.ingredients_text
    i = 0
    count = 0
    for j in range(num_embedded):
        open,close = find_inside(text,i)
        if open !=0 and close !=0:
          count += dat.ingredients_text[open:close].count(',')
          count_row = dat.ingredients_text[0:close].count(',') - count
          if count_row >=0:
            dat['string'+str(j)] = dat.ingredients_text[open:close]
            dat['ing_string'+str(j)] = count_row
        else: break
        i = close+1
    return dat

In [210]:
# for row in range(len(datatemp)):
#     text = datatemp.iloc[row].ingredients_text
#     i = 0
#     count = 0
#     for j in range(10):
#       open,close = find_inside(text,i)
#       if open !=0 and close !=0:
#         datatemp.iloc[row]['string'+str(j)] = dat.ingredients_text[open:close]
#         count += datatemp.iloc[row].ingredients_text[open:close].count(',')
#         count_row = datatemp.iloc[row].ingredients_text[0:close].count(',') - count
#         datatemp.iloc[row]['ing_string'+str(j)] = count_row
#       else: break
#       i = close+1

In [19]:
len(datatemp)

5

In [20]:
l=[]
for row in range(len(datatemp)):
    dat = datatemp.iloc[row]
    a = inside_par(5,dat)
    l.append(a)
    data_new = pd.concat(l)

In [21]:
l[2].ingredients_text

'pecorino bì©chamel sauce 32% (water, s immedmil powder,wheatflour, butter (mil ), cream (mil ), pecorino cheese 1.3% (sheepmil , salt, rennet), salt, sugar, nutmeg), tomato and vegetable sauce 24.4% (tomato pulp 15.8%, water, sunflower oil, onion, carrot,wheatstarch, grilled red peppers 0.5%,celery, cream (mil ), salt, basil, sugar, chives, papri a, oregano, turmeric, pepper), coo edeggpasta 21.3% (durumwheatsemolina, water,egg), vegetables in varying proportions 15.6% (grilled courgette, grilled aubergine, semi-dried tomatoes, grilled red peppers, mushrooms), cheese 6.6% (mozzarella cheese (mil , salt, microbial rennet), pecorino cheese (sheepmil , salt, rennet)),wheatfibre.allergy advice: for allergens, see ingredients in bold. may contain: soya.contains:mil '

In [22]:
l[2]

product_id                                                       11902758
snapshot_id                                                          1082
product_list_name                                                   23608
product_name                                                        23959
url                                                                 29699
ingredients_text        pecorino bì©chamel sauce 32% (water, s immedmi...
energy_per_100                                                     505 kj
fat_per_100                                                          6.0g
saturates_per_100                                                   3.1g)
salt_per_100                                                         0.8g
sugar_per_100                                                       3.2g)
carbohydrate_per_100                                                  11g
protein_per_100                                                      5.0g
fibre_per_100                                                        1.4g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             6511
name                                                                 3589
main_category                                                          24
department                                                            306
aisle                                                                1715
shelf                                                                 192
string0                 water, s immedmil powder,wheatflour, butter (m...
ing_string0                                                             0
string1                 tomato pulp 15.8%, water, sunflower oil, onion...
ing_string1                                                             1
string2                                     durumwheatsemolina, water,egg
ing_string2                                                             2
string3                 grilled courgette, grilled aubergine, semi-dri...
ing_string3                                                             3
string4                 mozzarella cheese (mil , salt, microbial renne...
ing_string4                                                             4
Name: 232326, dtype: object

In [23]:
a = inside_par(10,datatemp.iloc[0])
a

product_id                                                       11902756
snapshot_id                                                          1082
product_list_name                                                   23607
product_name                                                        23958
url                                                                 29925
ingredients_text        mascarpone cream 50% (wa er, mascarpone 11% (m...
energy_per_100                                                     973 kj
fat_per_100                                                           13g
saturates_per_100                                                   9.5g)
salt_per_100                                                        0.14g
sugar_per_100                                                        16g)
carbohydrate_per_100                                                  24g
protein_per_100                                                      4.5g
fibre_per_100                                                        1.3g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             6511
name                                                                 3589
main_category                                                          24
department                                                            306
aisle                                                                1715
shelf                                                                 192
string0                 wa er, mascarpone 11% (milk, cream (milk), aci...
ing_string0                                                             0
string1                 wa er, sugar, glucose syrup, soluble coffee 2%...
ing_string1                                                             1
Name: 232324, dtype: object

' auce 38.7% (fi handcru tacean tock (water,fi h,cru tacean , carrot , onion,celery), white wine 5.6%, extra virgin olive oil,  unflower oil, onion, garlic 1.2%,  alt, par ley 0.3%, anchovy pa te (anchovie  (fi h),  unflower oil,  alt), chilli pepper, white pepper), mu  el  24% (mollu c ),  quid 17% (mollu c ), tomatoe  12%,  hrimp  5% (cru tacean ), clam  3% (mollu c ), par ley.allergy advice: for allergen ,  ee ingredient  in bold. warning! thi  product may contain piece  of  hell.contain :fi h,cru tacean ,celery,mollu c '

In [139]:
datatemp

,product_id,snapshot_id,product_list_name,product_name,url,ingredients_text,energy_per_100,fat_per_100,saturates_per_100,salt_per_100,...,serving,serving_data,serving_value,serving_unit,Retailer,name,main_category,department,aisle,shelf
232324,11902756,1082,23607,23958,29925,"mascarpone cream 50% (wa er, mascarpone 11% (m...",973 kj,13g,9.5g),0.14g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232325,11902757,1082,23595,23946,29694,"auce 38.7% (fi handcru tacean tock (water,fi ...",678 kj,16g,2.1g),0.52g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232326,11902758,1082,23608,23959,29699,"pecorino bì©chamel sauce 32% (water, s immedmi...",505 kj,6.0g,3.1g),0.8g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232327,11902759,1082,23603,23954,29697,"tomato sauce 55.6% (tomato puree, onion, water...",539 kj,6.2g,2.7g),0.6g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232328,11902760,1082,23591,23942,29692,"clam al a 44.4% (clam tock (mollu c ), olive...",814 kj,20g,2.6g),0.33g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192

In [137]:
x

,product_id,snapshot_id,product_list_name,product_name,url,ingredients_text,energy_per_100,fat_per_100,saturates_per_100,salt_per_100,...,serving,serving_data,serving_value,serving_unit,Retailer,name,main_category,department,aisle,shelf
232324,11902756,1082,23607,23958,29925,"mascarpone cream 50% (wa er, mascarpone 11% (m...",973 kj,13g,9.5g),0.14g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232325,11902757,1082,23595,23946,29694,"auce 38.7% (fi handcru tacean tock (water,fi ...",678 kj,16g,2.1g),0.52g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232326,11902758,1082,23608,23959,29699,"pecorino bì©chamel sauce 32% (water, s immedmi...",505 kj,6.0g,3.1g),0.8g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232327,11902759,1082,23603,23954,29697,"tomato sauce 55.6% (tomato puree, onion, water...",539 kj,6.2g,2.7g),0.6g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192
232328,11902760,1082,23591,23942,29692,"clam al a 44.4% (clam tock (mollu c ), olive...",814 kj,20g,2.6g),0.33g,...,NaN,NaN,NaN,NaN,6511,3589,24,306,1715,192

In [91]:
from zmq.constants import NULL
embedded = 'keep'
num_embedded = 10
if embedded != 'embedded':
  for i in range(num_embedded):
    dat['string'+str(i)] = None
  for i in range(num_embedded):
    dat['ing_string'+str(i)] = None
text = dat.ingredients_text
print(text)
for j in range(num_embedded):
    num_char = len(dat)
    start_1=[]
    end_1 = []
    start_2 =[]
    end_2 = []
    a = re.search("[A-z](\s)?\)(\s?),(\s)?[A-z]|\)(\s)?\)(\s)?,(\s)?[A-z]",text)
    b = re.search("\([A-z]*\)",text)
    c = re.search("[A-z](\s)\)(\s)?,(\s)?\*(\s)?[A-z]",text)
    d = re.search("[A-z]\)(\s)?,(\s)?\*(\s)?[A-z]",text)
    # print(text)
    if a is None:
      a = []
    else: a = list(a.span())
    if b is None:
      b= []
    else: b= list(b.span()[1])
    if c is None:
      c = []
    else: c = list(c.span()[0]+2)
    if d is None:
      d = []
    else: d = list(d.span()[1]+1)
    end_1 = min(a+b+c+d)
    end_1 = end_1+1
    start_1 = re.finditer("\(",text[0:end_1])

    star = []
    for i in start_1:
        s = list(i.span())
        star += s
    start_1 = star[0:int(len(star)/2)]
    k = len(start_1)
    print(k, start_1)
    # print(k)
    open_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\(") 
    close_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\)") 
    logic_check = dat.ingredients_text[0:start_1[k-1]-1:].count('\(') == dat.ingredients_text[0:start_1[k-1]-1:].count('\)')

    while k>0 and open_1 != close_1 and open_1 is not None and close_1 is not None and logic_check is True:
      open_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\(") 
      close_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\)") 
      if open_1 == close_1:
        k = k
      else: 
        if open_1 !=close_1:
                 k = k-1
    start_1 = start_1[k]


    start_21 = re.search('\\([0-9]{1,2}%\\)(\\s)?\\([^0-9]',text)
    start_22 = re.search("[A-z](\\s)?\\([^0-9]",text)
    start_23= re.search("\\([0-9]{1,2}(\\.)[0-9]{1,2}%\\)(\\s)?\\([^0-9]",text)
    start_24 = re.search("[0-9]{1,2}%(\\s)?\\([^0-9]",text)
    start_25 = re.search("[0-9]{1,2}(\\.)[0-9]{1,2}%(\\s)?\\([^0-9]",text)
    start_26 = re.search("\\([0-9]{1,2}%\\)(\\,)?(\\s)?\\([^0-9]",text)
    start_27 = re.search("in varying proportions\\) \\(Courgette",text)
    start_28 = re.search('(\\s)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]',text)
    start_29 = re.search("(\\s)[0-9]{1,2},[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",text)
    start_2_10 = re.search("(\\s)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",text)
    start_2_11 = re.search("(\\s)[0-9]{1,2}(\\.)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",text)
    start_2_12 = re.search("(\\s)\\([0-9]{1,2}%,(\\s)[A-Z]",text)
    start_2_13 = re.search("\\([0-9]{1,2}(\\s)%\\)(\\s)\\([A-z]",text)
    start_2_14 = re.search("Vegetables(\\s)\\([0-9].[0-9]%",text)
    start_2_15 = re.search('\\([0-9]{1,2}%\\):(\\s)\\([A-z]',text)
    start_2_16 = re.search("Vegetables(\\s)\\([0-9][0-9].[0-9]%",text)
    start_2_17 = re.search("over dr. weight\\) \\([A-z]",text)
    start_2_18 = re.search("Brown Flour \\(50%",text)
    start_2_19 = re.search("Gherkins, \\(Gh",text)
    start_2_20 = re.search("Chocolate \\([0-9]{1,2}%\\)(\\s)-(\\s)\\(Sug",text)
    start_2_21 = re.search("%,(\\s)\\([A-z]",text)
    start_2_22 = re.search("\\(Edible Wafer",text)
    start_2_23 = re.search("\\(100%\\)(\\s)\\([A-z]",text)
    if start_21 is None:
      start_21 = []
    else: start_21 = [start_21.span()[1]-1]
    if start_22 is None:
      start_22 = []
    else: start_22 = [start_22.span()[1]-1]
    if start_23 is None:
      start_23 = []
    else: start_23=[start_23.span()[1]-1]
    if start_24 is None:
      start_24 = []
    else: start_24=[start_24.span()[1]-1]
    if start_25 is None:
      start_25 = []
    else: start_25=[start_25.span()[1]-1]
    if start_26 is None:
      start_26 = []
    else: start_26=[start_26.span()[1]-1]
    if start_27 is None:
      start_27 = []
    else: start_27=[start_27.span()[1]-9]
    if start_28 is None:
      start_28 = []
    else: start_28=[start_28.span()[1]-1]
    if start_29 is None:
      start_29 = []
    else: start_29=[start_29.span()[1]-1]
    if start_2_10 is None:
      start_2_10 = []
    else: start_2_10=[start_2_10.span()[1]-1]
    if start_2_11 is None:
      start_2_11 = []
    else: start_2_11=[start_2_11.span()[1]-1]
    if start_2_12 is None:
      start_2_12 = []
    else: start_2_12=[start_2_12.span()[0]+1]
    if start_2_13 is None:
      start_2_13 = []
    else: start_2_13=[start_2_13.span()[1]-2]
    if start_2_14 is None:
      start_2_14 = []
    else: start_2_14=[start_2_14.span()[1]-4]
    if start_2_15 is None:
      start_2_15 = []
    else: start_2_15=[start_2_15.span()[1]-2]
    if start_2_16 is None:
      start_2_16 = []
    else: start_2_16=[start_2_16.span()[1]-5]
    if start_2_17 is None:
      start_2_17 = []
    else: start_2_17= [start_2_17.span()[1]-1]
    if start_2_18 is None:
      start_2_18 = []
    else: start_2_18= [start_2_18.span()[1]-3]
    if start_2_19 is None:
      start_2_19 = []
    else: start_2_19= [start_2_19.span()[1]-3]
    if start_2_20 is None:
      start_2_20 = []
    else: start_2_20= [start_2_20.span()[1]-3]
    if start_2_21 is None:
      start_2_21 = []
    else: start_2_21= [start_2_21.span()[1]-2]
    if start_2_22 is None:
      start_2_22 = []
    else: start_2_22= list(start_2_22.span()[0])
    if start_2_23 is None:
      start_2_23 = []
    else: start_2_23=list(start_2_23.span()[1]-1)

    start_2 = min(start_21+start_22+start_23+start_24+start_25+start_26+start_27+start_28+start_29+start_2_10+start_2_11+start_2_12+start_2_13+start_2_14+
                  start_2_15+start_2_16+start_2_17+start_2_18+start_2_19+start_2_20+start_2_21+start_2_22+start_2_23)
    # print(start_1,end_1)
    if start_1 is not None and start_1 is not math.inf and start_2 is not None and start_2 is not math.inf:
      # if start_1 == start_2:
        if embedded != 'embedded':
          dat['string'+str(j)] = text[start_1:end_1]
          print(start_1,end_1)
          dat['ing_string'+str(j)] = text[0:start_1].count(',')+1
    text = text[end_1:]

pecorino bì©chamel sauce 32% (water, s immedmil powder,wheatflour, butter (mil ), cream (mil ), pecorino cheese 1.3% (sheepmil , salt, rennet), salt, sugar, nutmeg), tomato and vegetable sauce 24.4% (tomato pulp 15.8%, water, sunflower oil, onion, carrot,wheatstarch, grilled red peppers 0.5%,celery, cream (mil ), salt, basil, sugar, chives, papri a, oregano, turmeric, pepper), coo edeggpasta 21.3% (durumwheatsemolina, water,egg), vegetables in varying proportions 15.6% (grilled courgette, grilled aubergine, semi-dried tomatoes, grilled red peppers, mushrooms), cheese 6.6% (mozzarella cheese (mil , salt, microbial rennet), pecorino cheese (sheepmil , salt, rennet)),wheatfibre.
2 [29, 30]

IndexError: ignored

In [85]:
dat

product_id                                                       11902758
snapshot_id                                                          1082
product_list_name                                                   23608
product_name                                                        23959
url                                                                 29699
ingredients_text        pecorino bì©chamel sauce 32% (water, s immedmi...
energy_per_100                                                     505 kj
fat_per_100                                                          6.0g
saturates_per_100                                                   3.1g)
salt_per_100                                                         0.8g
sugar_per_100                                                       3.2g)
carbohydrate_per_100                                                  11g
protein_per_100                                                      5.0g
fibre_per_100                                                        1.4g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             6511
name                                                                 3589
main_category                                                          24
department                                                            306
aisle                                                                1715
shelf                                                                 192
string0                                                              None
string1                                                              None
string2                                                              None
string3                                                              None
string4                                                              None
string5                                                              None
string6                                                              None
string7                                                              None
string8                                                              None
string9                                                              None
ing_string0                                                          None
ing_string1                                                          None
ing_string2                                                          None
ing_string3                                                          None
ing_string4                                                          None
ing_string5                                                          None
ing_string6                                                          None
ing_string7                                                          None
ing_string8                                                          None
ing_string9                                                          None
Name: 232326, dtype: object

In [65]:
k = len(start_1)
start_1 = start_1[k-1]
start_1

30

In [66]:
start_1
dat.ingredients_text[30]

'w'

In [92]:
from zmq.constants import NULL
embedded = 'keep'
num_embedded = 10
if embedded != 'embedded':
  for i in range(num_embedded):
    dat['string'+str(i)] = None
  for i in range(num_embedded):
    dat['ing_string'+str(i)] = None
text = dat.ingredients_text
print(text)

pecorino bì©chamel sauce 32% (water, s immedmil powder,wheatflour, butter (mil ), cream (mil ), pecorino cheese 1.3% (sheepmil , salt, rennet), salt, sugar, nutmeg), tomato and vegetable sauce 24.4% (tomato pulp 15.8%, water, sunflower oil, onion, carrot,wheatstarch, grilled red peppers 0.5%,celery, cream (mil ), salt, basil, sugar, chives, papri a, oregano, turmeric, pepper), coo edeggpasta 21.3% (durumwheatsemolina, water,egg), vegetables in varying proportions 15.6% (grilled courgette, grilled aubergine, semi-dried tomatoes, grilled red peppers, mushrooms), cheese 6.6% (mozzarella cheese (mil , salt, microbial rennet), pecorino cheese (sheepmil , salt, rennet)),wheatfibre.

In [95]:
num_char = len(dat)
start_1=[]
end_1 = []
start_2 =[]
end_2 = []
a = re.search("[A-z](\s)?\)(\s?),(\s)?[A-z]|\)(\s)?\)(\s)?,(\s)?[A-z]",text)
b = re.search("\([A-z]*\)",text)
c = re.search("[A-z](\s)\)(\s)?,(\s)?\*(\s)?[A-z]",text)
d = re.search("[A-z]\)(\s)?,(\s)?\*(\s)?[A-z]",text)
# print(text)
if a is None:
  a = []
else: a = list(a.span())
if b is None:
  b= []
else: b= list(b.span()[1])
if c is None:
  c = []
else: c = list(c.span()[0]+2)
if d is None:
  d = []
else: d = list(d.span()[1]+1)
end_1 = min(a+b+c+d)
end_1 = end_1+1
start_1 = re.finditer("\(",text[0:end_1])

star = []
for i in start_1:
    s = list(i.span())
    star += s
start_1 = star[0:int(len(star)/2)]
k = len(start_1)

open_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\(") 
close_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\)") 
logic_check = dat.ingredients_text[0:start_1[k-1]-1:].count('\(') == dat.ingredients_text[0:start_1[k-1]-1:].count('\)')

In [98]:
start_1
k

2

In [99]:
while k>0 and open_1 != close_1 and open_1 is not None and close_1 is not None and logic_check is True:
      open_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\(") 
      close_1 = dat.ingredients_text[start_1[k-1]:end_1].count("\)") 
      if open_1 == close_1:
        k = k
      else: 
        if open_1 !=close_1:
                 k = k-1
start_1 = start_1[k-1]

In [100]:
start_21 = re.search('\\([0-9]{1,2}%\\)(\\s)?\\([^0-9]',dat.ingredients_text)
start_22 = re.search("[A-z](\\s)?\\([^0-9]",dat.ingredients_text)
start_23= re.search("\\([0-9]{1,2}(\\.)[0-9]{1,2}%\\)(\\s)?\\([^0-9]",dat.ingredients_text)
start_24 = re.search("[0-9]{1,2}%(\\s)?\\([^0-9]",dat.ingredients_text)
start_25 = re.search("[0-9]{1,2}(\\.)[0-9]{1,2}%(\\s)?\\([^0-9]",dat.ingredients_text)
start_26 = re.search("\\([0-9]{1,2}%\\)(\\,)?(\\s)?\\([^0-9]",dat.ingredients_text)
start_27 = re.search("in varying proportions\\) \\(Courgette",dat.ingredients_text)
start_28 = re.search('(\\s)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]',dat.ingredients_text)
start_29 = re.search("(\\s)[0-9]{1,2},[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",dat.ingredients_text)
start_2_10 = re.search("(\\s)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",dat.ingredients_text)
start_2_11 = re.search("(\\s)[0-9]{1,2}(\\.)[0-9]{1,2}(\\s)%(\\s)?\\([^0-9]",dat.ingredients_text)
start_2_12 = re.search("(\\s)\\([0-9]{1,2}%,(\\s)[A-Z]",dat.ingredients_text)
start_2_13 = re.search("\\([0-9]{1,2}(\\s)%\\)(\\s)\\([A-z]",dat.ingredients_text)
start_2_14 = re.search("Vegetables(\\s)\\([0-9].[0-9]%",dat.ingredients_text)
start_2_15 = re.search('\\([0-9]{1,2}%\\):(\\s)\\([A-z]',dat.ingredients_text)
start_2_16 = re.search("Vegetables(\\s)\\([0-9][0-9].[0-9]%",dat.ingredients_text)
start_2_17 = re.search("over dr. weight\\) \\([A-z]",dat.ingredients_text)
start_2_18 = re.search("Brown Flour \\(50%",dat.ingredients_text)
start_2_19 = re.search("Gherkins, \\(Gh",dat.ingredients_text)
start_2_20 = re.search("Chocolate \\([0-9]{1,2}%\\)(\\s)-(\\s)\\(Sug",dat.ingredients_text)
start_2_21 = re.search("%,(\\s)\\([A-z]",dat.ingredients_text)
start_2_22 = re.search("\\(Edible Wafer",dat.ingredients_text)
start_2_23 = re.search("\\(100%\\)(\\s)\\([A-z]",dat.ingredients_text)
if start_21 is None:
  start_21 = []
else: start_21 = [start_21.span()[1]-1]
if start_22 is None:
  start_22 = []
else: start_22 = [start_22.span()[1]-1]
if start_23 is None:
  start_23 = []
else: start_23=[start_23.span()[1]-1]
if start_24 is None:
  start_24 = []
else: start_24=[start_24.span()[1]-1]
if start_25 is None:
  start_25 = []
else: start_25=[start_25.span()[1]-1]
if start_26 is None:
  start_26 = []
else: start_26=[start_26.span()[1]-1]
if start_27 is None:
  start_27 = []
else: start_27=[start_27.span()[1]-9]
if start_28 is None:
  start_28 = []
else: start_28=[start_28.span()[1]-1]
if start_29 is None:
  start_29 = []
else: start_29=[start_29.span()[1]-1]
if start_2_10 is None:
  start_2_10 = []
else: start_2_10=[start_2_10.span()[1]-1]
if start_2_11 is None:
  start_2_11 = []
else: start_2_11=[start_2_11.span()[1]-1]
if start_2_12 is None:
  start_2_12 = []
else: start_2_12=[start_2_12.span()[0]+1]
if start_2_13 is None:
  start_2_13 = []
else: start_2_13=[start_2_13.span()[1]-2]
if start_2_14 is None:
  start_2_14 = []
else: start_2_14=[start_2_14.span()[1]-4]
if start_2_15 is None:
  start_2_15 = []
else: start_2_15=[start_2_15.span()[1]-2]
if start_2_16 is None:
  start_2_16 = []
else: start_2_16=[start_2_16.span()[1]-5]
if start_2_17 is None:
  start_2_17 = []
else: start_2_17= [start_2_17.span()[1]-1]
if start_2_18 is None:
  start_2_18 = []
else: start_2_18= [start_2_18.span()[1]-3]
if start_2_19 is None:
  start_2_19 = []
else: start_2_19= [start_2_19.span()[1]-3]
if start_2_20 is None:
  start_2_20 = []
else: start_2_20= [start_2_20.span()[1]-3]
if start_2_21 is None:
  start_2_21 = []
else: start_2_21= [start_2_21.span()[1]-2]
if start_2_22 is None:
  start_2_22 = []
else: start_2_22= list(start_2_22.span()[0])
if start_2_23 is None:
  start_2_23 = []
else: start_2_23=list(start_2_23.span()[1]-1)

In [101]:
start_2 = min(start_21+start_22+start_23+start_24+start_25+start_26+start_27+start_28+start_29+start_2_10+start_2_11+start_2_12+start_2_13+start_2_14+
              start_2_15+start_2_16+start_2_17+start_2_18+start_2_19+start_2_20+start_2_21+start_2_22+start_2_23)

In [105]:
start_2

30

In [42]:
import math
x=10
print(x is math.inf)

False

In [44]:
end_2 = re.search("\\)(\\s)?,(\\s)?[A-z]",dat.ingredients_text[start_2:num_char])

In [45]:
end_2

In [72]:
if start_1 != start_2 and start_1 is not None and start_2 is not None and start_1 is not math.inf and start_2 is not math.inf:
    a = re.search("\\)(\\s)?,(\\s)?[A-z]",dat.ingredients_text[start_2:num_char]).span()
    end_2 =a[0]+1+start_2
    if end_2 is math.inf:
      end_2 = start_2+re.search("\\)(\\s)?,(\\s)?[A-z]",dat.ingredients_text[start_2:num_char])
    open_par = dat.ingredients_text[start_2:end_2].count('\(')
    close_par = dat.ingredients_text[start_2:end_2].count('\)')
    counter = 1
    # for open_par < close_par and counter <= 25 and open_par is not None and close_par is not None:
    #     counter +=1
    #     tmp_stasrt = re.search('\(',dat.ingredients_text[0:start_2])
    #     tmp_start = tmp_start[0] #?
    #     start = tmp_start
    #     open_par = dat.ingredients_text[start_2:end_2].count('/(')
    #     close_par = dat.ingredients_text[start_2:end_2].count('/)')
    # tmp_end_2=0
    # if end_2 is not None and end_2 is not math.inf:
    #     counter = 1
    #     for close_par != open_par and counter <25 and tmp_end_2 is not math.inf:
    #         counter +=1
    #         tmp_end_2 =

In [75]:
end_1

78

In [102]:
for j in range(num_embedded):
    if start_1 is not None and start_1 is not math.inf and start_2 is not None and start_2 is not math.inf:
      if start_1 == start_2:
        if embedded != 'embedded':
          dat['string'+str(j)] = dat.ingredients_text[start_1:end_1]
          dat['ing_string'+str(j)] = dat.ingredients_text[0:start_1].count(',')+1

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

In [103]:
dat

product_id                                                       11902758
snapshot_id                                                          1082
product_list_name                                                   23608
product_name                                                        23959
url                                                                 29699
ingredients_text        pecorino bì©chamel sauce 32% (water, s immedmi...
energy_per_100                                                     505 kj
fat_per_100                                                          6.0g
saturates_per_100                                                   3.1g)
salt_per_100                                                         0.8g
sugar_per_100                                                       3.2g)
carbohydrate_per_100                                                  11g
protein_per_100                                                      5.0g
fibre_per_100                                                        1.4g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             6511
name                                                                 3589
main_category                                                          24
department                                                            306
aisle                                                                1715
shelf                                                                 192
string0                  water, s immedmil powder,wheatflour, butter (mil
string1                  water, s immedmil powder,wheatflour, butter (mil
string2                  water, s immedmil powder,wheatflour, butter (mil
string3                  water, s immedmil powder,wheatflour, butter (mil
string4                  water, s immedmil powder,wheatflour, butter (mil
string5                  water, s immedmil powder,wheatflour, butter (mil
string6                  water, s immedmil powder,wheatflour, butter (mil
string7                  water, s immedmil powder,wheatflour, butter (mil
string8                  water, s immedmil powder,wheatflour, butter (mil
string9                  water, s immedmil powder,wheatflour, butter (mil
ing_string0                                                             1
ing_string1                                                             1
ing_string2                                                             1
ing_string3                                                             1
ing_string4                                                             1
ing_string5                                                             1
ing_string6                                                             1
ing_string7                                                             1
ing_string8                                                             1
ing_string9                                                             1
Name: 232326, dtype: object

In [76]:
dat.ingredients_text[start_2:end_2]

TypeError: ignored

In [67]:
dat['string'+str(0)] = dat.ingredients_text[start_1:end_1]
dat

product_id                                                       11902759
snapshot_id                                                          1082
product_list_name                                                   23603
product_name                                                        23954
url                                                                 29697
ingredients_text        tomato sauce 55.6% (tomato puree, onion, water...
energy_per_100                                                     539 kj
fat_per_100                                                          6.2g
saturates_per_100                                                   2.7g)
salt_per_100                                                         0.6g
sugar_per_100                                                       3.0g)
carbohydrate_per_100                                                 4.1g
protein_per_100                                                     13.0g
fibre_per_100                                                        1.3g
serving                                                               NaN
serving_data                                                          NaN
serving_value                                                         NaN
serving_unit                                                          NaN
Retailer                                                             6511
name                                                                 3589
main_category                                                          24
department                                                            306
aisle                                                                1715
shelf                                                                 192
string0                 tomato puree, onion, water, chic en stoc  (wat...
string1                                                              None
string2                                                              None
string3                                                              None
string4                                                              None
string5                                                              None
string6                                                              None
string7                                                              None
string8                                                              None
string9                                                              None
ing_string0                                                          None
ing_string1                                                          None
ing_string2                                                          None
ing_string3                                                          None
ing_string4                                                          None
ing_string5                                                          None
ing_string6                                                          None
ing_string7                                                          None
ing_string8                                                          None
ing_string9                                                          None
Name: 232327, dtype: object

In [ ]:
def embeded_function(dat,
                     num_embedded,
                     ingredient_list,
                     rows,
                     embedded
                    )
    dat['ingrediant_col'] = dat['ingrediant_text']
    for i in rows:
      for j in range(num_embedded):

0                                                   Cheddar
1                                                   Cheddar
2                                                   Cheddar
3                               Butter (Milk), Salt (1.5%).
4                               Butter (Milk), Salt (1.5%).
                                ...
232324    Mascarpone cream 50% (water, mascarpone 11% (M...
232325    Sauce 38.7% (fishandcrustaceanstock (water,FIS...
232326    Pecorino bÌ©chamel sauce 32% (water, skimmedMI...
232327    Tomato sauce 55.6% (tomato puree, onion, water...
232328    Clam salsa 44.4% (clam stock (MOLLUSCS), olive...
Name: ingredients_text, Length: 232329, dtype: object

In [ ]:
data.ingredients_text.iloc[232324].split(',')

['Mascarpone cream 50% (water',
 ' mascarpone 11% (MILK',
 ' cream (MILK)',
 ' acidity regulator: E330)',
 ' skimmedMILK',
 ' cream (MILK)',
 ' coconut oil',
 ' sugar',
 ' dextrose',
 'EGGyolk',
 ' whole and skimmed powderedMILK',
 ' modified starch',
 ' stabilisers: E407',
 ' E415',
 ' E435',
 ' E471',
 ' E472b',
 ' salt',
 ' anti-caking: E509',
 ' flavourings',
 ' colour: E160a)',
 ' Coffee syrup (water',
 ' sugar',
 ' glucose syrup',
 ' soluble coffee 2%',
 ' coffee 0.1%',
 ' colour: E150d',
 ' natural flavourings',
 ' Savoiardi biscuits 15% (WHEATflour',
 ' sugar',
 'EGG',
 ' raising agents: E500',
 ' E503',
 ' glucose syrup',
 ' natural flavourings',
 ' salt)',
 ' Cocoa powder.ALLERGY ADVICE: FOR ALLERGENS',
 ' SEE INGREDIENTS IN BOLD. MAY CONTAIN NUTS (ALMONDS',
 ' HAZELNUTS',
 ' WALNUTS',
 ' PISTACHIOS)',
 ' SOYA.Contains:milk',
 'egg',
 'wheat']

In [ ]:
ingrediant

0         81696
1         81696
2         81696
3         83821
4         83821
          ...
232324    29925
232325    29694
232326    29699
232327    29697
232328    29692
Name: url, Length: 232329, dtype: int64